### ISSUE TITLE
function "daysInMonths" returns wrong number of days in months 6 and 11.

### ISSUE THREAD

**Issue by s11eta1yek** [arashm/JCal#2]
Hello

In your file "jdate.js", in lines 676 and 680, there is a flawed comparison, that returns false values in month 6 and 11.

  if (calcedMonth < 6) {
    return 31;
  }
  
  if (calcedMonth < 11) {
    return 30;
  }

Just change the "<" to "<=" and it'll work correctly.  I appreciate your library.

**Comment by arashm** [comment]
Hi. In JS's official date from std, months are 0 based (January is returned as `0`, e.g. `new Date('01 Jan 1970 00:00:00 GMT').getMonth()` returns `0`). The library tries to be compatible with JS's paradigm.

**Comment by arashm** [comment]
Also this lib hasn't been maintained for a long time. I suggest using something else really :)

**Comment by s11eta1yek** [comment]
I understand but the real issue is this part of the code from lines 669 to 674.

if (calcedMonth < 0) {
        calcedMonth += 12;
        calcedYear -= 1;
      } else if (calcedMonth === 0) {
        calcedMonth = 12;
      }

I noticed that,  when  "calcedMonth === 0", it equates "calcedMonth" to 12, and it breaks the logic of the code. it really doesn't matter.

I'm really sorry to bother you. I was just using the library and noticed this issue. I won't comment on it again. thanks for the reply ;)
